### ISSUE TITLE
Change th name!

### ISSUE THREAD

**Issue by VincenzoCarlino** [dbjohnson/reactable-search#4]
Hi, how can I change the name dislayed in <th> element?
Because I cannot make a json whit blank spaces.
There is a solution?

**Comment by dbjohnson** [comment]
Hi @Vincenzo1997, please see example below - you can use arbitrary string values for the JSON object keys, which flow through to the <th>.  Please let me know if it helps.

```js
import SearchTable from 'reactable-search';
import ReactDOM from 'react-dom';

const rows = [
  {'foo bar': 1, 'baz qux': 2},
  {'foo bar': 2, 'baz qux': 3},
];

ReactDOM.render(
  <SearchTable
    searchPrompt="Type to search"
    rows={rows}/>,
  document.getElementByID("root")
);
```
